export const ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  tasks: '/tasks',
  taskDetail: (id: string) => `/tasks/${id}`,
  customers: '/customers',
  customerDetail: (id: string) => `/customers/${id}`,
  accountOpening: '/account-opening',
  accountOpeningSelectType: '/account-opening/select-type',
  accountOpeningIndividualSavings: '/account-opening/individual-savings',
  accountOpeningIndividualCurrent: '/account-opening/individual-current',
  accountOpeningDetail: (requestId: string) => `/account-opening/${requestId}`,
  accountUpgrade: (accountId: string) => `/account-upgrade/${accountId}`,
  staff: '/staff',
  staffDetail: (staffId: string) => `/staff/${staffId}`,
  workflowReviews: '/workflow/reviews',
  workflowReviewDetail: (id: string) => `/workflow/reviews/${id}`,
  workflowCompliance: '/workflow/compliance',
  workflowComplianceDetail: (id: string) => `/workflow/compliance/${id}`,
  workflowLienRequests: '/workflow/lien-requests',
  operationsReferences: '/operations/references',
  loans: '/loans',
  loansNew: '/loans/new',
  settings: '/settings',
  settingsPin: '/settings/pin',
  more: '/more',
} as const;
